### ISSUE TITLE
Favorilerin hero transitiondan etkilenmesi

### ISSUE THREAD

**Issue by MehmetKaranlik** [VB-CORE/hatayi_yasat#113]
Favorilerden sayfasından geri dönerken hero transition tetikleniyor buglu duruyor.

https://github.com/VB-CORE/life_client/assets/89414084/7412c1e5-c623-45ac-b925-09eac4a67d97

**Comment by VB10** [comment]
bunuda yeni kitle hallederiz geçiyorum biri de almamış ki üstüne :)
