### ISSUE TITLE
Öneri

### ISSUE THREAD

**Issue by kadirbekar** [VB-CORE/hatayi_yasat#114]
Mekanlar tabında aşağı scroll edince sayfanın başına scroll eden buton ekleyebiliriz veya SliverAppBar ile yukarı scroll hareketi ile search bar gösterilebilir

**Comment by kadirbekar** [comment]
@MehmetKaranlik ile test ederken mehmet denk geldi, burs başvurusu sırasında klavye açılınca IOS ta klavyeyi kapatmak için çözüm eklenebilir. Uygulamanın diğer sayfalarında da aynı şekilde.

1. öneri - material app seviyesinde gesture detector ile sarmalayıp, boş bir yere tıklanınca kapatılabilir, bütün uygulamaya eklenir,

2. öneri - scrollable olan base bir widget'a aksiyon olarak scroll ederken klavyenin kapanma aksiyonu verilmeyi deneyebiliriz

**Comment by VB10** [comment]
@kadirbekar teşekkürler bunları yeni kitle bilrikte entegre edeceğiz
