### ISSUE TITLE
Ayarlar sayfası

### ISSUE THREAD

**Issue by VB10** [VB-CORE/hatayi_yasat#123]
**Description**

EXPANSION OLACAK

- sol üstte ayarlar sliver olacak şekilde hep yapılacak
- en üstte takımı gösteren bir alan ve buraya batığında takımın detalyaırnı görecek
- change language basınca bir bottom sheet ile aktif uygulama dili gösterilecek ve diğer dilla seçim yapıp kaydet derse o dile geçilecek
- bildiimler kapılı ise changen otificaton gözükecek ve yine basılıdğında app dışında ayalra gidilip açılmasına bkaılacak
- app settings yan sayfaya geçiecek uygulama versiyon, marketing sitesi ve detaylar gözükecek proje hakkında
- get supprot basınca doğrudan bir sheet açılacak ve iki özellik verilecek bir mail atma özelliği burada samete ve bana yollandırlaacak sekilde hazılanır iki tweet gödnerme özelliği burada hazır bir template yapılıp o bağlanacak
- favorilerim tabı olacak ve mekanlar göüzekecek burada 

**Screen Preview**
![image](https://github.com/VB-CORE/life_client/assets/17102578/664d829d-5467-4056-b975-c0c86297cd64)

**Comment by VB10** [comment]
aldim @BerkSartik

**Comment by mysCod3r** [comment]
@VB10 hocam şuanlık buraya kadar hazırladım. Contact us içerisini dolduracağım
| | |
|-|-|
|![image](https://github.com/VB-CORE/life_client/assets/76634747/02318bfd-ad51-46cf-90a7-7b899ee1bdc5)|![image](https://github.com/VB-CORE/life_client/assets/76634747/525e5e0e-60ee-4c7f-a856-3ef077c665a9)

**Comment by mysCod3r** [comment]
@VB10 hocam önceki yazdığım kodları yanlışlıkla direkt `feature/new_uikit_v2` branchine pushlamıştım. sizle konuştum revert edecektiniz. yazdığım tüm kodlar [feature/#123](https://github.com/VB-CORE/life_client/tree/feature/%23123) bu branchte, revert ettiğiniz zaman pr açacağım.

|||
|-|-|
|![image](https://github.com/VB-CORE/life_client/assets/76634747/7c05f014-d72b-48a0-923d-7e5ef33c11c6)|![image](https://github.com/VB-CORE/life_client/assets/76634747/a72e9201-5cb2-4ad5-a80a-42f538b6e163)

**Comment by mysCod3r** [comment]
#170 de yapıldı
