### ISSUE TITLE
Form ekranları genel

### ISSUE THREAD

**Issue by VB10** [VB-CORE/hatayi_yasat#126]
**Description**
Tüm istek sayfalarımız bu şekilde olacak.

- komponenleter ortak olacak ve tasarım bu şekilde bğalnacak
- image yükleme dosya yükleme ekteki gibi olacak
- tüm alanlar required olacak ve eklendikten sonra gönderme aktif olacak
- gönderme yapılrıken sayfadan çıkalamayacak ve ortada yüklenme ile alakalı bu lottie göükecek
https://lottiefiles.com/animations/uploading-Ylgo5f3hai

bu sayfa burs, place, proje içinde olacak

**Screen Preview**
![image](https://github.com/VB-CORE/life_client/assets/17102578/3ab04778-b27c-48a8-b8da-5a4db23db48a)

**Comment by VB10** [comment]
aldim verdim

**Comment by VB10** [comment]
genel ekranlar su sekilde:
![image](https://github.com/VB-CORE/life_client/assets/17102578/ed6172f0-8cd2-4391-8306-5825d2572e51)


===

![image](https://github.com/VB-CORE/life_client/assets/17102578/0f4162c3-f2d9-4fdd-99ef-e75c474f5cab)

**Comment by burakJs** [comment]
burs ve proje ekranlarını aldım
