### ISSUE TITLE
[v2-Component] Button Design

### ISSUE THREAD

**Issue by BerkSartik** [VB-CORE/hatayi_yasat#128]
![image](https://github.com/VB-CORE/life_client/assets/48359825/33e27575-0bbb-4664-885e-3261c4b7b506)
![image](https://github.com/VB-CORE/life_client/assets/48359825/f199ec91-1797-4621-bc76-3cc22c756983)

**Comment by VB10** [comment]
@MehmetKaranlik ne durumdayız
