### ISSUE TITLE
[v2-Component] Textfield

### ISSUE THREAD

**Issue by BerkSartik** [VB-CORE/hatayi_yasat#130]
![image](https://github.com/VB-CORE/life_client/assets/48359825/431dad41-c8c2-4d5a-b118-8f7552e106a4)

**Comment by VB10** [comment]
ready to use 
<img width="357" alt="image" src="https://github.com/VB-CORE/life_client/assets/17102578/b6fd061c-659c-40de-a665-6c1c5e8720ac">
