### ISSUE TITLE
[v2-Component] General Author Widget

### ISSUE THREAD

**Issue by BerkSartik** [VB-CORE/hatayi_yasat#135]
![image](https://github.com/VB-CORE/life_client/assets/48359825/3350599a-1718-4a7c-8b0c-cc812c27538d)
![image](https://github.com/VB-CORE/life_client/assets/48359825/8c7175d4-ff27-479c-bc56-b96ebb47fedc)
![image](https://github.com/VB-CORE/life_client/assets/48359825/13d266b6-b92e-4fce-a98e-7dffada1bace)

**Comment by VB10** [comment]
@BerkSartik ne durudmayız canım

**Comment by BerkSartik** [comment]
> @BerkSartik ne durudmayız canım

Dışarıdayım eve geçince pr açacağım
