### ISSUE TITLE
[v2-Component] Search Textfield

### ISSUE THREAD

**Issue by BerkSartik** [VB-CORE/hatayi_yasat#137]
![image](https://github.com/VB-CORE/life_client/assets/48359825/8d148435-8b80-4f6e-bd06-a98cce03449b)
![image](https://github.com/VB-CORE/life_client/assets/48359825/c47e43e5-6630-4b54-94a4-cfa242e5809e)

**Comment by VB10** [comment]
hazir
![image](https://github.com/VB-CORE/life_client/assets/17102578/a7163de7-035d-4139-b84c-7e560fe0d078)
