### ISSUE TITLE
[v2-Component] Iconed Text

### ISSUE THREAD

**Issue by BerkSartik** [VB-CORE/hatayi_yasat#139]
![image](https://github.com/VB-CORE/life_client/assets/48359825/066d8ff6-c084-4bb0-b69c-dd3ed745d532)
![image](https://github.com/VB-CORE/life_client/assets/48359825/bb38f023-63dc-41f3-9e6c-0d2b4353bb08)

**Comment by VB10** [comment]
aldım

**Comment by VB10** [comment]
added
