### ISSUE TITLE
[v2-Component] Place Card

### ISSUE THREAD

**Issue by BerkSartik** [VB-CORE/hatayi_yasat#142]
![image](https://github.com/VB-CORE/life_client/assets/48359825/7ffff7ec-bfd5-4f1b-ad7a-d081efafb689)

**Comment by VB10** [comment]
@kadirbekar ne durumadyız canım

**Comment by kadirbekar** [comment]
> @kadirbekar ne durumadyız canım

Salı günü 23.59 olmadan PR açık hocamkee

**Comment by kadirbekar** [comment]
Card tasarımının görünümü için StoreModel modeli kullanıldı. Development sürecinde gerçek model ile güncelleme yapabiliriz.
