### ISSUE TITLE
Detail Pages

### ISSUE THREAD

**Issue by BerkSartik** [VB-CORE/hatayi_yasat#164]
#### Detay sayfası ortak widgetlardan oluşuyor.
- AuthorListtile Widget
- IconWithText Widget
- title ve açıklama için ayrıca bir Widget bulunuyor.

####  Detayı yapılacak sayfalar
- Place
- News
- Event

 
![Screenshot_2](https://github.com/VB-CORE/life_client/assets/48359825/cfb7d713-7a7a-4837-8ddf-0a833ff37253)![Screenshot_3](https://github.com/VB-CORE/life_client/assets/48359825/f3a56913-4772-4650-afd7-cf1d277023c2)

**Comment by VB10** [comment]
@BerkSartik @burakJs
