### ISSUE TITLE
OnBoard Navigation Issue

### ISSUE THREAD

**Issue by burakJs** [VB-CORE/hatayi_yasat#180]
**Description**
- Onboard sayfasından splashe gidildiği zaman splashten home sayfasına gidilmiyor splashte kalıyor

**Screen Preview**

**Comment by BerkSartik** [comment]
@burakJs bu sorun çözüldüyse issue kapatabilir misin?

**Comment by burakJs** [comment]
> @burakJs bu sorun çözüldüyse issue kapatabilir misin?

Çözüldü çözüldü bu elimize sağlık
