### ISSUE TITLE
v4 bug fixes

### ISSUE THREAD

**Issue by BerkSartik** [VB-CORE/hatayi_yasat#182]
- [ ] anasayfada kategori alanı scrollable değil (bunu scrollable yaptığımız zaman cardlarda uzunluktan dolayı problem oluyor konuşmamız gerekiyor ne yapacağımızı)
- [x] favoriye eklenmiş işletme olduğunda tümünü temizle butonu işletmeleri kaldıramadı
- [ ] Speed dialda bulunan request sayfaları hala eskileri. Onları yeni sayfalar ile güncellemeliyiz.

- [x] dil değişince aynı sayfada bazı değerler değişmiyor
- [x] favoride eklenmiş bir işletme yokken tümünü temizle butonunu gizleyebiliriz
- [x] bize ulaşın alanında mail’e tıklayınca abc@gmail.com ‘a mesaj gönderiyor
- [x] ayarlar sayfasında bize ulaşın gibi expandable alanlar açıldığı zaman sayfanın en altına scroll olmadı

**Comment by BerkSartik** [comment]
`Bildirimleri açmak için uygulama adını listede göremedim` 
-> Bu problem neyden kaynaklı anlayamadım. Bildirimi açmak için tıklayınca Hatay'ı Yaşat telefon içi uygulama sayfasına yönlendiriyor 'android' kısmında. Oradan açılabiliyor. @kadirbekar hocam tam anlayabilmem için dönüş yaparsanız sevinirim
![image](https://github.com/VB-CORE/life_client/assets/48359825/ffd0a9d9-50c1-4e88-8045-afd11459519f)

**Comment by kadirbekar** [comment]
Selam hocam,

Bildirim izni check box'a tıklayınca dialog açılıyor, tamam dedikten sonra IOS cihazda uygulamaların olduğu bir liste sayfası açılıyor, o listede de hatayı yaşat uygulamasını göremedim, bu mesajı yazarken tekrar denedim ama aynı şekilde görünmedi

![image](https://github.com/VB-CORE/life_client/assets/34074484/336df14c-04a4-48fc-9799-820276ed9f5f)

**Comment by BerkSartik** [comment]
@kadirbekar ios test etme şansım yok ancak neyden kaynaklandığını araştırıp çözüm bulmaya çalışacağım.

Ana store uygulamasında yani eski halinde bu sorun var mı hocam onu test edebilir misiniz?

**Comment by kadirbekar** [comment]
Şöyle bir akış var şu an ki market versiyonunda. 

1- Uygulama yüklendi, ana sayfa açıldığında bildirimlere izin veriyor musunuz diyalog açıldı. İzin veriyorum. Sonrasında ayarlar sayfasına gidip var olan izni kaldırmak isteyince checkbox hiç kapanmıyor. Hep açık kalıyor.

2- İlk açılışta izin vermediğim zaman ayarlar sayfasında aktif ederken şu görüntü geliyor.

Bildirimleri aktif ediyorum fakat uygulamaya gelince checkbox aktif olmuyor, aktif olduğunu görebilmek için tekrar kapatıp açmak lazım, yoksa her seferinde bildirim açma ekranına atıyor. Bir kere aktif edilmiş ise 1. Akış tekrar ediyor

Test ettiğim 4.0.0(25) de bütün uygulamaların olduğu sayfaya atıyordu, aşağıdaki gibi Hatayı Yaşat uygulamasının detayını açıp bildirimleri aktif / pasif etme ekranına atmıyordu

![image](https://github.com/VB-CORE/life_client/assets/34074484/2bf865a7-1433-4213-bfb7-330f2c47086d)

![image](https://github.com/VB-CORE/life_client/assets/34074484/cdfa11d9-22a9-4b0b-8643-334ab186dcbd)
