### ISSUE TITLE
Bug Notes

### ISSUE THREAD

**Issue by burakJs** [VB-CORE/hatayi_yasat#195]
**Description**

- [x] Wpden bir mesaj gonder seceneginin gonderdigi mesaj yanlış
	- yanlış mesaj : Instance of '_StringExtension'
	- <img src="https://github.com/VB-CORE/life_client/assets/70351342/7a2bbfcc-b1ca-419a-bf2e-433fad59d8f8" width=250>

<hr/>

- [x] İşaretlediğim yerden basarak filtreye gidince filtre çalışmıyor ve homa'a yönlendiriyor
	- <img src="https://github.com/VB-CORE/life_client/assets/70351342/4d52e116-4f77-4660-ba09-0c0667b90ca5" width=250>

<hr/>

- [x] Burs basvurusunda boyut limiti calismiyor 100 kb sinir yaziyor fakat 967 kb yukledim

<hr/>

- [ ] 	- Burs ekranına gidilir
	- Herhangi bir inputa basılıp klavye açılır
	- Sonrasında dosya yüklemeye basılır
	- Açılan dosya yükleme ekranı kapatılır
	- Burs ekranında sol üstteki geri tuşuna basılarak home sayfasına geri dönülür ve klavye kapanmıyor
	- Ekran Resmi :
		- <img src="https://github.com/VB-CORE/life_client/assets/70351342/1ba329ab-4c9a-47b3-92f2-7a3ce2bb523e" width=250>

<hr/>

- [x] Favori sayfasında arama çalışmıyor

<hr/>

- [x] Öneri:
	- Favori sayfasına gidilir
	- Favorilere eklenen yerin detay sayfasına gidilir
	- Çarpıya basınca home sayfasına geri dönüyor bence yine favorilere dönmeli

**Screen Preview**

**Comment by VB10** [comment]
@burakJs favori sayfasinda search calsiiyor fakat 0 ise hep ilk olani gosteriyor

burs issueleri kaldi sadece @BerkSartik sana atadim knk onu

**Comment by BerkSartik** [comment]
Tamamdir hocam @VB10

**Comment by BerkSartik** [comment]
@burakJs bu ekranda klavye kalma case'ini fixleyemedim çünkü androidde yaşamıyorum. Yani geri geldiğimde klavye kapalı oluyor. Ayrıca son güncel halinde başka bir yere tıklanınca klavyenin kapanması için kod eklendi diye biliyorum. Emin olmak adına branch kontrolü yapabilir misin? (feature/new_uikit_v2) Ona göre müsait olan bir ios kullanıcısından fixlemesini isteyelim
