### ISSUE TITLE
Version 4.0.0 Bugs

### ISSUE THREAD

**Issue by mysCod3r** [VB-CORE/hatayi_yasat#200]
- [ ] > categories (filtre seçilir -> show result) > filter result page açılır. Geri gelince anasayfaya atıyor. Filtre ekranına geri dönmesini bekledim şahsen. 
- [ ] Aynı şekilde listelenen sonuçlardan bir detaya gidince (görsel geç yükleniyor, loading yok. 1-2 sn sonra Bir anda fotoğraf ekleniyor.) ve geri buyonu yok direkt çarpı var. Anasayfaya geri dönüyor. Burda da yine bie önceki sayfaya geri dönmesini bekledim. (Misal spor u filtreleyip ordaki tüm işletmelere sırayla bakmak istiyorsam bir işletmeye bakıp kapatıp her seferinde yeniden filtre işlemlerini yapmam gerekecek.)

- [x] favorilerden tümünü sil butonu işin onay dialog hazırlamıştım. Pr açık duruyor. Yeni pakette onay dialog yok. 

- [ ] home tabinde iken floatingactionbar çevresi şeffaf, diğer e tabde iken çevresi şeffaf değil. 

- [ ] yeni burs talebi oluştururken klavye açıkken pickere geçip geri dönünce klavye kapanmıyor. İlla ekrandaki textfieldlara tıklanıp sonra boş vi yere tıklanması gerekiyor. (Ekran videosu wp gurubuna atılmıştır.) -> çözüm önerisi: LifeCycleManager yazılır. State== resume ise focusNode instance dan klavye kapatılır. TabView bu widget ile sarmalanır. 
- [ ] Yeni burs başvurusu alındıktan sonra onay dialog açılıyor. Arkasında textfieldlar temizlenip tekrardan form validete çalışıyor. Dialog açık iken arkasında textfieldların altında error mesajları görünüyor. (Proje başvuru ekranında da aynısı mevcut)

- [x] Yeni proje ekranında datetime seçerken iptal edince datetime now seçiliyordu. Bunun fixini yazmıştım. Pr açık kalmış yeni pakette mevcut değil. 

- [ ] Form ekranlarında klavye açıkken form gönder butonları görünmüyor. Klavyenin kapanması için boş bir yere tıklamak gerekiyor ama her yer textfield olduğu için boş yete tıklamak zor. Çözüm önerisi -> listview in keyboarddismiss özelliği kullanılabilir. Drag olunca klavyeyi kapatabiliriz.

**Comment by VB10** [comment]
completed
