### ISSUE TITLE
v5 features

### ISSUE THREAD

**Issue by BerkSartik** [VB-CORE/hatayi_yasat#203]
- Bildirimlere link ekleme

**Comment by VB10** [comment]
- Firebase crashhlytics ios kısmı düzeltilecek

**Comment by VB10** [comment]
- görünümünü değiştir özelliği eklenecek 4 lü veya şuanki gibi tekli card olacak:

https://github.com/VB-CORE/life_client/assets/17102578/47c82465-7108-4261-9b24-4cb5e1798335

**Comment by VB10** [comment]
bu sametten gelen ıstekler @BerkSartik ne düşünüyorsun reklam ve link dışında diğerleri çok mantıklı gelmedi koyulacak yer konusunda belki anlaşmalı yerleri bu hale getirebiliriz diye geldi aklıma

– REKLAM ALANI AYARLANACAK, görsel cizimde belirtildiği gibi fıltrelemenın tam alt kısmına veya ust kısmına

Bildirimlere link ekleme seçeneği gelirse yerel üreticiyi desteklemek adına bir alan yapılabilir
Valilik Gastronomi çarşısı gibi özel alanların yerını gösterecek bir alan yapılabilir. İçerisinde yer alan firmaları isim anlamında listeyebiliriz. Tek konum zaten hepsi
BİM Gibi özel kurumlara konumlarını listeleme satmaya calısıyorum. 134 şubesı var hatay’da. Örneğin bunları listelemek istersek, Hatay’ın 15 ilçesinde bunların adresini yazmak ısteyebiliriz. Manuel benım girişimde olacak. Örneğin
BİM BUTONU tıkladı, Antakya Şube: adres ( konuma gitmesine gerek yok manuel text olabilir ) , Odabaşı Şube vs
Uygulama içerisinde kullanımı arttırıcı fikirleriniz vardı onları sizlerde yazarsanız ben de görebilirim :)

**Comment by BerkSartik** [comment]
1. Reklam ve link konusunda bence okey hocam. 
2. Diğer konular mantıklı gelmedi bana. Ama ekstra mekan öne çıkarma gibi bir sistem ekleyip yine anasayfada en üstte listelenme olayını ekleyebiliriz reklam alanı gibi yapıp. Diğer türlü çok zorlama olur bence. Amacımıza uygun hizmet etmiyor yani o özellikler.

Neden hizmet etmiyor derseniz bim'in öne çıkmasına ihtiyacı yok zaten kendi reklamıyla çıkabilir ama yerel esnafı günlük olarak öne çıkarırsak insanlara daha fazla yardımcı olabiliriz diye düşünüyorum.

**Comment by BerkSartik** [comment]
1. Bir kategoride ilçe seçip mekanlara bakıp işletmenin profiline girdiğimizde geri çıkarken ana sayfaya atıyor. Bence bu düzeltilmeli. Bir önceki arayüze atarsa kolaylık olur.
2. İşletmelerin hangi saatler aralığında açık olduğunu gösteren bir kısım açılırsa daha iyi olur. Uygulamaya giriş-çıkışı arttırır.
3. İşletmeler puanlama sistemiyle değerlendirilebilirse, bu insanlar için referans olabilir.
4. Bence uygulamada mutlaka ulaşım kısmı açılmalı. Belediye otobüs durakları, saatleri ve ilçe dolmuşlarının kalkış noktası, saatleri, numaraları vb. bilgiler eklenirse Hatay'a gelen yabancı insanlar ve Hatay'da yaşayanlar için büyük kolaylık olur.
5. Hatay'da düzenlenecek etkinliklerle alakalı bir kategori de açılabilir. Bölgedeki insanlar sosyalleşmek, zaman geçirmek istiyor. Bu yüzden faydalı olacağını düşünüyorum.

**Comment by VB10** [comment]
1-2 ok digerleri çok mantıklı değil bizim için belki ulaşım eklenebilir ama buda ciddi bir data ister akış ister bakmak lazım

**Comment by VB10** [comment]
tamamlandi
