### ISSUE TITLE
[CLIENT] ana sayfada görünüm değişme opsiyonu verilerek 4lü grid şeklinde gösterim sağlanacak

### ISSUE THREAD

**Issue by BerkSartik** [VB-CORE/hatayi_yasat#205]
İş süresi: 3 gün
iş detayı:

- search alnında compnentin yanına eklenecek ve görünümü değiştir bottom sheeti gelip seçime göre ekran güncelenecek
- 4lu grıd opsıyonu verilecek ve bu seçim saklanacak(uygulama cache kısmında oluştuuran client modeli için saklnacak)
- ilk başlangıçta 4lü yeni tasarım set edilecek

**Comment by VB10** [comment]
eklendı
