### ISSUE TITLE
[CLIENT] Anasayfaya sort eklenecek

### ISSUE THREAD

**Issue by BerkSartik** [VB-CORE/hatayi_yasat#206]
iş süresi: 3 gün
iş detayı:

- ana sayfada search alanının yanına icon koyulacak sorting iconu ve bu icon field alanı.
- buna baslınca bottom sheet acılıp sıralamayı değiştir diyecek
- ilgili seçim cache kısmında saklanacak
- genel bir modelimiz varsa onunun içine yoksa client diye bir model yapılıp içine cachelnecek seçim ve app açılıkren buna bakılacak

**Comment by VB10** [comment]
tamamalandı
