### ISSUE TITLE
[CLIENT] search ve filtremele işlemi sonrasında ana sayfaya dönüyor

### ISSUE THREAD

**Issue by BerkSartik** [VB-CORE/hatayi_yasat#208]
iş süresi: 1gün
iş detayı

- searche yazdın, künefe yazdın, sekiz seçenek, biri seçilir ve üstüne geri geldiğinde ana sayfaya gidiyor bunu yerine seaach ekranında son ekranda kalması gerekiyor

- fitlereme buttona bastık, bir filtreme yaptık ili seçi işi alanı seç butona bas sonra çıkan sonuçlardan birine gtttin veya gitmedin geri gelmeye çalıştığında yine ana sayfa atıyor bunun bekleneni filtremelede kalması en son seçilenlerle.

**Comment by VB10** [comment]
fıxlendı
