### ISSUE TITLE
[CLIENT] Zincir Mağazalar Eklenecek

### ISSUE THREAD

**Issue by BerkSartik** [VB-CORE/hatayi_yasat#210]
- zincir marketlerin kendine ait sayfası olacak.
- Burada zincir marketlerin(bim, turkcel vb.) ana adları sıralanacak.
- Tıklanılan marketin detay sayfasında sisteme girilen tüm adresleri birer satır satır gösterilecek ve isterse buradan o adrese, çalışma saatleri veya konuma gidebilecek.
- bu ilgii alanların adı ilçe bilgisi lat long yönlendirme de yaparız
- push gelecek
- açıklama için özel site linki eklenebiir

**Comment by VB10** [comment]
bilreştirdim gerek kalmadı
