### ISSUE TITLE
[CLIENT] Reklam alanı eklenecek

### ISSUE THREAD

**Issue by BerkSartik** [VB-CORE/hatayi_yasat#211]
- ana sayfada üst kısımda bir banner alan olacak
- burada admin tarafından yüklenen resimler gösterilecek
- bir senaryoda bu resimlere tıklanarak ilgili linkler varsa orası açılacak
- ve bu resimler carousel olarak otomatik oynar olabilecek
- push notification ile bildirim atılmış halide olacak o gelen pushlarda  ana sayfa açık kalacak

<img src="https://github.com/VB-CORE/life_client/assets/48359825/1c522b7f-4542-4932-a794-8a8e0485003f" width="35%">

**Comment by VB10** [comment]
@BerkSartik buna gerek kalmadı client admin birleştirdim
