### ISSUE TITLE
[ADMIN-Client] İşletmelerin çalışma saati bilgileri alanı eklenecek

### ISSUE THREAD

**Issue by VB10** [VB-CORE/hatayi_yasat#212]
İş süresi: 2 gün
İş açıklaması:
Admin
- Admin tarafında firmalara saat eklenme alanı gelecek ve yeni girilenlerde zorunlu olacak
- İşletme update ederkende saatler required olacak

Client:
- yeni başvurlarda çalışma saati alanı eklenecek ve açılış kapanış saati zorunlu olacak
- bu materialın hour dialogu olacak seçecek ve o kısım gözükecek
- detayda kapanış saati sonrası giridğinde kapalı açık gibi bir alan eklenecek

**Comment by VB10** [comment]
@kadirbekar admin tarafı ile alaklı @MehmetKaranlik @mysCod3r her zaman destek olur

**Comment by kadirbekar** [comment]
okidir hocam, danke

**Comment by kadirbekar** [comment]
Client tarafı ile başladım hocam @VB10  FYI, buradaki kontrolleri ve testi yapıp admin tarafı ile devam ediyor olacağım

**Comment by kadirbekar** [comment]
Bu akşam PR geliyorum hocamke FYI @VB10
