### ISSUE TITLE
[ADMIN-Client] Zincir Mağazalar Eklenecek

### ISSUE THREAD

**Issue by VB10** [VB-CORE/hatayi_yasat#213]
İş süresi: 7 gün
İş detayı:

admin
- Yeni alan açılacak ve zincir market adı istenecek altında birden fazla telefon yeni firmalar girilebilecek ardından bunlar güncellenebilecek ve mağazanın açıklama imkanıda olacak.
- burada admin tarafında ayrı bir sayfa olacak ve burada açık zincirler listenecek
- aynı sayfada ekleme opsiyonu verilecek ve o sayfada en üstte: zincir market logo resim link yada sisteme yükleme,
- çalışma saati de alınacak
 zincir market adı, zincir market açıklaması ve sitesi yer alacak.
- bu kısımıdan sonra sürekli bir artı butonu ile alt şubelerinn adı, adresi, ve lat long bilgisia alınacak
- işlem sonunda uygulamaya bildirim gidip sayfa açılacak
- datalar firebase işlenecek ve en son kayıt etmeden emin misin sorulacak
- update etme yine adminde verilecek

Client: 

- zincir marketler alanı gelecek appbar en sağ üç nokta butonunda
- basılınca liste gelecek
- burada tasarım olarak grid şeklinde firmalar gösterilecek logolarıyla 
- basılınca en üstte logo olacak adı açıklaması sitesi aynı place detay sayfası gibi altındada girilen sub firmaların adları adresleri ve açıklamaları bunlar bir expansion tile gibi.
- lat long olanlara haritada aç opsiyonu

**Comment by VB10** [comment]
@mysCod3r yine admin tarafını halletikten sonra konuşalım client tarafına biz gireibliriz @MehmetKaranlik her zaman admin taraıfnın başı

**Comment by VB10** [comment]
@burakJs sende bu taskın clientı yaparsın
@mysCod3r admin birlikte çalışırsınz

**Comment by mysCod3r** [comment]
![WhatsApp Görsel 2024-03-02 saat 15 50 19_b5889d0b](https://github.com/VB-CORE/life_client/assets/76634747/d10b71cf-cf81-4af8-a0ff-fd726f880950)

**Comment by mysCod3r** [comment]
Admin tarafı halledildi. Shared ve admin tarafında prlar açıldı. İlgili ekran videosu pr a eklendi. 
Not: push notification gönderme kısmı yapılmadı. Notification için client tarafı bitince ve normalde gönderdiğimizfen farklı bir content olacağını düşündüğümden netleştiği zaman gerekli ekleme entegre edilebileceği için o kısım şuanlık bağlanmadı.

**Comment by BerkSartik** [comment]
@mysCod3r Samet hocayla iletişime geçtim. Zincir mağazalar için push notification olmasın. Manuel olarak halletmek daha doğru olur dedi. Entegre etmeye gerek kalmadı yani bilgin olsun

**Comment by VB10** [comment]
@mysCod3r

**Comment by VB10** [comment]
@burakJs tamamlandı sanırıım

**Comment by VB10** [comment]
@burakJs @mysCod3r tamamlandi mi burasi

**Comment by mysCod3r** [comment]
@VB10 evet hocam tamamlandı

**Comment by VB10** [comment]
@MehmetKaranlik sana bırakıyorum re write yapma adına koymus olalım
