### ISSUE TITLE
[ADMIN- Client] Reklam ekleme alanı

### ISSUE THREAD

**Issue by VB10** [VB-CORE/hatayi_yasat#214]
iş süresi: 5 gün
iş detayı:

Admin:
- admin tarafında banner eklemek için bir alan yapılacak
- bu alan resim ve link alacak ve her girilen için push atılacak
- girilen reklamları sıralayabilmek belki birinci sıraya önceliğe göre koymak her açıldığında hangisi gözükecek vs.

- bu datalara index vereceğiz ve bu indexler güncellenebilir olacak isterse admin tarafında
- bu sıralama bittikten sonra yukarıda kaydet butonu ile datalar güncellenir

Client:
- Ana sayfa search kısmınını butona çevirip appbara koyacağız.
- ana sayfada kategorilerin üstüne banner alanı gelecek burada resimler oynyacak
- resimlere https://pub.dev/packages/carousel_slider gibi bir paketle bağlanıp oto sürekli dönecek
- bottom sheet açılacak resime basıldıktan sonra linki aç veya paylaş butonu gelecek
- push notification ile bildirim atılmış halide olacak o gelen pushlarda  ana sayfa açık kalacak

<img src="https://github.com/VB-CORE/life_client/assets/48359825/1c522b7f-4542-4932-a794-8a8e0485003f" width="35%">

**Comment by E-MRE** [comment]
Client için açılan issue var sanırım bu ikisini de kapsıyor. Admin için aklıma gelenleri yazayım.

Bence bu banner alanı için bazı bilgileri saklamakta yarar var. Örneğin gösterim sayısı, tıklama sayısı, benzersiz gösterim sayısı gibi metrikler. Bunları analytics ile tutmak mümkün gibi fakat kendi yöntemlerimizi de uygulayabiliriz sanki.

Ayrıca buraya reklam verenler neye göre ücretlendirilecek? Gün üzerinden mi yoksa gösterim üzerinden mi?

**Comment by E-MRE** [comment]
Client tarafında gösterim için hiç reklam olmadığı, tek reklam olması ve çok reklam olması durumlarını kararlaştırmakta fayda var. Bence ilk bir iki hafta reklam olmasa bile isteyenlerin o alana reklam verebileceğini ifade eden resimler koyabiliriz. 

Resim boyutları standart mı olacak? Bir de url gelir diye tahmin ediyorum,  cache network image işimize yarar bu konuda. resimler yüklenirken hata alırsa ne olacak bunu da kararlaştırsak fena olmaz.

**Comment by VB10** [comment]
@E-MRE sen cok konusmsusn bu taskı senle berke verdim

ikiniz admin client tarafını götürrsünüz

**Comment by E-MRE** [comment]
Ben bu gece projeyi silip sıfırdan yeniden çekeyim, temiz bir şekilde ilerlerim.

**Comment by BerkSartik** [comment]
@VB10  hocam issue'da reklam için sadece link ve resim olarak yazmışız başlık ve küçük bir detay yazısı eklememiz iyi olmaz mı? Yani reklama tıklandığında popup çıkartıp reklam detayını görüntületebiliriz. O detaya da örneğin "HATAYIYASAT15 kodu ile %15 indirim alabilirsiniz" tarzında bir şeyler yazabiliriz. Ne düşünüyorsunuz?

**Comment by E-MRE** [comment]
> @VB10 hocam issue'da reklam için sadece link ve resim olarak yazmışız başlık ve küçük bir detay yazısı eklememiz iyi olmaz mı? Yani reklama tıklandığında popup çıkartıp reklam detayını görüntületebiliriz. O detaya da örneğin "HATAYIYASAT15 kodu ile %15 indirim alabilirsiniz" tarzında bir şeyler yazabiliriz. Ne düşünüyorsunuz?

Olabilir aslında ama bu tür açıklamalar reklam alanında olmaz mı zaten? oradaki banner da firma adı ve resmi dışında indirim veya ne tarz reklam veriyorsa onu da dahil edeceklerini düşünüyorum. Yemeksepeti örnek olarak verilebilir.

**Comment by BerkSartik** [comment]
@E-MRE haklısınız hocam dediğiniz gibi olur muhtemelen

**Comment by VB10** [comment]
@E-MRE @BerkSartik biizm burada beklentimiz su adam resmi verecek biz guncelleyecegiz bu linkede tiklayinca detay text acilacak altinda kopyala veya ac opsyionu ile app disina aticaz

**Comment by BerkSartik** [comment]
@E-MRE hocam reklamla ilgili işlemleri bitirdim. Yani ekleme, düzenleme ve silme kısmını. Sadece dataları sıralama kısmı kaldı. Sıralama ve client tarafında kalanları müsait olduğunuz zamanda (akşam vakitlerinde) birlikte yapsak olur mu ?

**Comment by E-MRE** [comment]
> @E-MRE hocam reklamla ilgili işlemleri bitirdim. Yani ekleme, düzenleme ve silme kısmını. Sadece dataları sıralama kısmı kaldı. Sıralama ve client tarafında kalanları müsait olduğunuz zamanda (akşam vakitlerinde) birlikte yapsak olur mu ?

@BerkSartik olur tabiki. Bu akşam müsait olamayacağım. yarın veya salı akşamı müsaitim.

**Comment by BerkSartik** [comment]
Admin kısmı için reklam ekleme aktif edildi. "Reklam sıralama" eksik. @VB10 

Samet hocayla "reklam notification" konusunu konuşulacak.

**Comment by VB10** [comment]
@BerkSartik reklam alanında bir tane muhkakak reklam vermek isteyenler için banneri bırakırz diye planlıyorum bunu firebase ekleyebilir miyiz projede 3 ana resim vardı onlardan birini vs yaparak

**Comment by BerkSartik** [comment]
@VB10 gerekli eklemeyi yaptım hocam
