### ISSUE TITLE
[ADMIN- Client] Push notify gönderirken link ekleme

### ISSUE THREAD

**Issue by VB10** [VB-CORE/hatayi_yasat#215]
iş süresi: 4 gün
iş detayı:

Admin
 - web tarafında push yolladıgımız kısımda link alanı eklenecek ve link açıklama alanı verilecek.
 - eklenen link alanında link validasyonu olacak (direk oto eger eklerse muhakkak link olmalı)
 - bilidrim atmadan önce butona bastıktan sonra emin misiniz gideecek mesaj title body ve link bu şeklidne kısım gözükecek
 - atılan bildirimleri firebase child altında besliyorduk bu beslediğimiz kısıma body diye bir alan ekleyip bu bodyi girelim.
 - bu girilen link ve detayı push notificion ana kısımda gözükmeyecek dokununca detayda gözükecek

Client

- gelen pusha Dokunduktan sonra bir detay sayfası açılacak burada olan kısımda title Bildirim detayı olacak ve üst kısımda notificion açıklaması, ilgili link ve link detayı alt alta yer alacak link tıklanabilir olacak.
- link yanında paylaş gibi bir button olacak.
- tasarım ekranı var olan uikte uygun sakin renkleri vs yapılmalı

**Comment by VB10** [comment]
@MehmetKaranlik admın tarafını bıitiridkten sonra client tarafını başka bir arkadaşda atayaibliriz

**Comment by MehmetKaranlik** [comment]
Admin tarafı tamamlandı, firebase body'de link, notification collectionunda id kısmı url olarak geliyor.

**Comment by VB10** [comment]
@MehmetKaranlik  client tarafına bakabildin mi

**Comment by VB10** [comment]
sanırım bu bıttı @kadirbekar @MehmetKaranlik

**Comment by MehmetKaranlik** [comment]
Yes
