### ISSUE TITLE
ana sitemize destek veya bildiri alanı eklenecek

### ISSUE THREAD

**Issue by VB10** [VB-CORE/hatayi_yasat#216]
iş süresi: 1 gün
iş detayı: 
 - web sitesine bilgi verme veya fikir verme adına bir google form alanı eklenecek
 - web sitesine ekibe katılma formu eklenecek

**Comment by E-MRE** [comment]
Form eklendikten sonra bildirim vs gelecek mi? Form dolduranlar başvuru takibi vs yapabilecek mi yoksa biz mi dönüş sağlayacağız?

**Comment by VB10** [comment]
@E-MRE google form düşün oradan Samet ben kontrol edeceğim app ile alakası olmayacak hiç

**Comment by VB10** [comment]
sametten formlar alınıp sıteye eklenecek

**Comment by BerkSartik** [comment]
İletişim formu eklendi.

**Comment by BerkSartik** [comment]
https://www.hatayiyasat.com/iletisim
https://www.hatayiyasat.com/bize-kat%C4%B1l

@VB10 Samet hocayla görüşüp formları güncelleyip siteye ekledim.

**Comment by VB10** [comment]
@BerkSartik eline sağlık <3
