### ISSUE TITLE
[Client] Release buglari

### ISSUE THREAD

**Issue by BerkSartik** [VB-CORE/hatayi_yasat#220]
İş ilanı panelden girildikten sonra herkese bildirim gidiyor. Ancak iş ilanı kısmı boş gözüküyor. Beyazlığa tıklayınca ilan detayı açılıyor.

<img src="https://github.com/VB-CORE/life_client/assets/48359825/42bd3bb6-191f-4d8c-b28c-673eef696831" width="25%">
<img src="https://github.com/VB-CORE/life_client/assets/48359825/4e77686a-2cbf-4f2e-be7a-7ef5a4164803" width="25%">

**Comment by VB10** [comment]
bottom barlarda arka taraf opacity olmuyor ana sayfada gozuktu gibi

**Comment by VB10** [comment]
tamamlandı
