### ISSUE TITLE
[DATABASE] Fonksiyonlar eklenecek.

### ISSUE THREAD

**Issue by BerkSartik** [VB-CORE/hatayi_yasat#221]
insertte search update atıyoruz ama delete de sanırım yapmadık

**Comment by VB10** [comment]
@MehmetKaranlik buraya ilgili curl bizim ana postmende varsa oradan da bakarım paylasır mısın ben bir deneyeyim şunu bir de silinmiş olanlar olabilir istersen sen bir genel update atarsın

**Comment by VB10** [comment]
bu tamam kapatıyorum
