### ISSUE TITLE
v5.0.0 Issues

### ISSUE THREAD

**Issue by burakJs** [VB-CORE/hatayi_yasat#240]
**Description**

- [x] Cacheden okunarak gelen mekan için beğenilenlere kaydetmeye çalışınca alınan hata. Genel olarak beğenmede bir problem var

  - **Ekstra not:** bu hatadan dolayı uygulama splash sayfasında kaldı
  - <img src="https://github.com/VB-CORE/life_client/assets/70351342/227a2d8a-c39c-4c7b-b68c-278f40c5ce0f" width=700>

<hr>

- [x] Easy localization bug

  - <img src="https://github.com/VB-CORE/life_client/assets/70351342/9c132245-0430-4263-a839-007fc41a9e35" width=250>
  - <img src="https://github.com/VB-CORE/life_client/assets/70351342/7d80a090-6321-4cba-a1d8-7a4898804d8a" width=250>

<hr>

- [x] Ayarlarda bize ulaşın kısmının ilk açıldığı zaman overflow var

  - <img src="https://github.com/VB-CORE/life_client/assets/70351342/af69ef46-5bdf-4484-8637-2ab497006324" width=250>

**Comment by VB10** [comment]
@burakJs genel sorunlar fixlendi

**Comment by VB10** [comment]
Unutulmamali
 - gereksiz lottieler silienecek
 - whatsnew icin gerkeli textler girilecek

@BerkSartik @burakJs

**Comment by BerkSartik** [comment]
- [x] Reklam linki açma konusunda

![image](https://github.com/VB-CORE/life_client/assets/48359825/f4366cb6-721a-4097-82f9-db3f39ee1dfb)

----

- [x] Küçük card tasarımında favori butonu görünmesi zor oluyor

![image](https://github.com/VB-CORE/life_client/assets/48359825/54394c96-0504-4808-97c6-011087589a7e)


- Filtreleme ile sonuç bulunamadığı durumda özel kurumlar bulunamadı hatası veriyor.
