### ISSUE TITLE
Release 5.0.0 issue

### ISSUE THREAD

**Issue by VB10** [VB-CORE/hatayi_yasat#251]

**Comment by grafikheriff** [comment]
![search bug](https://github.com/VB-CORE/life_client/assets/160399398/579e78da-49b9-469a-8355-6d487a903b26)
![search bug2](https://github.com/VB-CORE/life_client/assets/160399398/30753dad-5389-480a-a1de-c40067c37eb9)
Search butonu tam anlamıyla çalışmıyor.
Örneğin Efsay Kuruyemişte isim güncellenmiş. Efsay diye arattığında Efsay Kuruyemiş çıkıyor içine girince tam adı olan Efsay Kuruyemiş Kahve olarak gözüküyor.

**Comment by VB10** [comment]
@grafikheriff bu sorun ne durumda bro

**Comment by grafikheriff** [comment]
Bunu baştan ekleyip çözmüştük.
