### ISSUE TITLE
Release 6.0.0

### ISSUE THREAD

**Issue by VB10** [VB-CORE/hatayi_yasat#254]
https://www.figma.com/design/XD2el1v68VF7Pog8T6Ufp9/Hatay'%C4%B1-Ya%C5%9Fat?node-id=0-1&t=fTMkMApzcnG4384z-0

**Comment by grafikheriff** [comment]
_**Turizm ile ilgili uygulamayı kullandırıcı bir çalışma. Bu tamamen bizim uygulamaya uygun hangi yapıyı öngörürseniz o olur. Tarihi yerleri listeleyebiliriz ilçesel olarak. Bu güncellemenin en can alıcı şeyi bu olmalı, turızm rehberıyız de dıyebılırız**_

**Zincir Mağazalar Sekmesinin aynısı Konteyner Çarşılar şeklinde ekleme ( 3 noktaya tıkladın orada )**

**Kategorilere Otomotiv Eklenecek**

**_Filtreleme veya arama da firma listelendiğinde firmalar alt alta text olarak geliyor. Bunların ekledıklerı fotoğraflarla lıstelenmesı konusunda cok talep geldı. Böyle ınsanlar anlayamıyoruz karmasık gelıyor dıyorlar. Mumkun mudur._**

_Diğer bi cok gelen talep ana sayfa cok karmasık gelıyor denılıyor. Bana göre iyi durumda alıştırmaktan yanayım. bu konuda onerılerınız varsa._

**Comment by BerkSartik** [comment]
Zincir mağazalar kısmını hali hazırda zaten bu çarşılar için kullanılacak şekilde ekledik. O gün yayın sırasında tartışma konumuz buydu yani. Ekstra olarak eklemek gereksiz kaçacaktır bence. Ama belli bir sebebten dolayı çıkarmak istiyorsanız o kısmı bilmiyorum.

Anasayfa konusunda karışıklık nerede var o kısmı belirtseler daha iyi olabilir. Halihazırda 3 tane ana başlığımız var zaten çok karmaşıklık bir durum olduğunu düşünmüyorum.

Geri kalanlar okey bence de ve turizm konusu ekstra etkili olabilir katılıyorum.

**Comment by kadirbekar** [comment]
Samet hocanın notları benim için de okeydir. 

Anasayfa kısmı için belki tasarım olarak biraz text styler ile oynanabilir. Siyah beyaz tasarımda İşletme adı, açıklaması birbirine benzediği için yakın gelmiştir diye düşüyorum bu şekilde bir yorum geldiği için.

@BerkSartik hocanın bahsettiği zincir mağazalar kısmını hatırlayamadım. Hatırlatma olması açısından tekrar bir konuşulabilir
@VB10

**Comment by E-MRE** [comment]
Benim ekstra ekleyeceğim pek bir madde yok. Sadece erasmus yıllarından olsa ne güzel olurdu dediğim şeyleri paylaşacağım. Ben bir tarihi bir yeri incelediğimde o yer hakkında pek bilgiye sahip değildim, dolayısıyla italya'da gittiğim yerlerde fazla keyif alamadım. Belki bu tarihi ve kültürel mekanların listelendiği seçilen mekanda da fotoğrafın kenarında köşesinde açıklamaları olan veya sesli anlatımı olan bir modül yapmak yararlı olabilir. Örnek vereyim isos antik kentini uygulamadan buldum ve detaya git dedim. karşıma fotoğraflar gelse ve orada sütun olduğunu varsayalım açıklamada da hakkında bilgiler verse, yana kaydırsam az ileride ki yapıya ait fotoğraf ve bilgiler. Böylece hem canlı canlı görüyor olurum mekanı hem bilgi edinirim. sesli anlatım da güzel olabilir. Sanal rehber gibi hava olur.

**Comment by grafikheriff** [comment]
emre hocamın yazdıkları gözümde canlandı enfes.

**Comment by mysCod3r** [comment]
yazılanların üstüne ekstra bir yorum yapamayacağım benim içinde okaydir
