### ISSUE TITLE
Turizm Modülü [Client]

### ISSUE THREAD

**Issue by VB10** [VB-CORE/hatayi_yasat#255]
**Description**
- Client tarafında harita üzerinde pinlenmiş noktlar göstereceğiz
- Bu pinler altta card olarak gözükecek ve cardlar değişince pine gidiecek
- Pinler arasında line çizilecek
- Pinlerin üzerine dokunuludğunda konuma git ve konum adı yer alacak

**Screen Preview**
<img width="609" alt="image" src="https://github.com/VB-CORE/life_client/assets/17102578/9d9fdd8e-d1c0-40cc-8c78-a6c7eaee497a">

**Comment by kadirbekar** [comment]
@E-MRE ile birlikte bunu aldık @VB10 hocam

**Comment by E-MRE** [comment]
İş Akışı:

- Gerekli paketlerin kurulumu
- İlgili sayfanın tetikleneceği kısımdan ilgili izinlerin alınması (konum vs)
- Haritaların yüklenmesi ve koordinatların girilmesi (başlangıç için dummy olabilir)
- Kartların gösterimi ve yukarıdaki maddelerin uygulanması
- Servisin bağlanması ve testlerin yapılması

**Comment by kadirbekar** [comment]
Çalıştığımız branch -> feature/255_tourism_module

@E-MRE  ile yaptığımız çalışma -> 

Maps ve çizgi çekebilmek için paketleri uygulamaya ekledik, paket kurulumunun tamamlanması için API_KEY değerlerinin girilmesi gerekiyor.
Lokasyon isteği için gerekli methodlar eklendi
Dummy FAB buton ile sayfa yönlendirilmesi sağlandı

**Comment by E-MRE** [comment]
- Sayfa içerisi yeniden oluşturuldu.
- Turistik yerlerin listelendiği slider ekranın altına eklendi
- Model oluşturuldu
- Mekanlar için card tasarlandı.
- Tıklandığında ilgili konuma zoom yapılacak şekilde ayarlandı.
- En az 2 konum seçildiğinde poly line çiziliyor fakat dümdüz çiziyor ve 2 den sonrasında da devam ediyor. bunu düzeltmek gerekecek.

@kadirbekar 

![image](https://github.com/VB-CORE/life_client/assets/34197392/2fd5e77c-4b1a-4cba-bf3b-b368c0ee2abf)
