### ISSUE TITLE
Filtreleme Sayfamız [Client]

### ISSUE THREAD

**Issue by VB10** [VB-CORE/hatayi_yasat#258]
**Description**

Fitlreleme sonucu sonrası gelen sayfada resim de eklenecek.

"Filtreleme veya arama da firma listelendiğinde firmalar alt alta text olarak geliyor. Bunların ekledıklerı fotoğraflarla lıstelenmesı konusunda cok talep geldı. Böyle ınsanlar anlayamıyoruz karmasık gelıyor dıyorlar"

**Screen Preview**

![image](https://github.com/VB-CORE/life_client/assets/17102578/89d1660d-946e-40a2-94c5-cdf35e773dae)

**Comment by burakJs** [comment]
Hocam bunu ben aldım

**Comment by VB10** [comment]
@burakJs afied

**Comment by burakJs** [comment]
Hocam pr açıldı
