### ISSUE TITLE
Release 6.0.0 Test Check

### ISSUE THREAD

**Issue by VB10** [VB-CORE/hatayi_yasat#268]
font size fixlenekecek 1

**Comment by BerkSartik** [comment]
- Haberler ve İş ilanları sayfasında tab'e tıklayarak değil sağa kaydırarak tab değiştirdiğimizde tab yenilenmiyor. (Haberler kısmında kalıyor)
- Yenilikler yazısı 5.0.0 release'i için eskide kalmış.

- Mekan detayda bazı işletmelerde böyle bir problem var. Sanırım iş yeri sahibi widget'ı ile ilgili
<img src='https://github.com/VB-CORE/life_client/assets/48359825/8073ab8b-230c-4364-9df7-af5f49d6ea34' width=28%>

**Comment by BerkSartik** [comment]
Update sonrası karşılaştığım hatalar:
- İngilizce yenilikler title'ı 5.0.0 kalmış. (içerik düzgün)
- Ayarlar > Uygulama hakkında kısmında bulunan webview çalışmıyor yüklemede kalıyor, site açılmıyor.
- Bir önceki yorumumda belirttiğim mekan detay kısmında title ve owner hala sıkıntılı duruyor biraz daha iyileşmiş olsada. Uzun isimlerde hala kayıyor. owner widget'ını alta almak daha iyi olabilir.

**Comment by VB10** [comment]
@BerkSartik 1. fix, webview aciliyor bende tam sorunu bakmak adina bir debug yapar misin. 3. case ile iglili ornek resimler atarsan bir bakalim benim telefondan belki tam ykalayamiyorum

**Comment by VB10** [comment]
@BerkSartik suan 3 max line ekledim widthi sabitledim ki ekrana gore olmasin 
<img width="481" alt="image" src="https://github.com/VB-CORE/life_client/assets/17102578/989709fa-bd3a-4f26-a1b4-4b64a724895c">

**Comment by BerkSartik** [comment]
@VB10 buyrun hocam bu webview hatası
![image](https://github.com/VB-CORE/life_client/assets/48359825/5b511095-deec-496e-b7b3-26640ec5ac14)

Crashlytics'e gönderdiği hatayıda ekliyorum hocam
![image](https://github.com/VB-CORE/life_client/assets/48359825/e672be65-8233-4755-b035-a682905c18eb)

Buda title kısmı için fix atmışsınız ama yinede koyayım dedim. Owner widget'ı üste veya alta almak daha sağlıklı olabilir diye düşünüyorum
<img src='https://github.com/VB-CORE/life_client/assets/48359825/8a859c69-61e1-49a3-959e-8f7540c2d2f0' width=25%>
