### ISSUE TITLE
[V7 - CLIENT] Girişimciler için link sayfası

### ISSUE THREAD

**Issue by BerkSartik** [VB-CORE/hatayi_yasat#275]
Yeni bir sayfa eklenerek burada kadın vb. girişimcilerin dataları görüntülenecek ve tıklandığında sayfalarına (insta, website vb.) yönlendirme yapılacak.

# Görüntülenecek datalar #
- Logo
- İsim
- Küçük bir açıklama (kesinleştirilmedi)

**Comment by VB10** [comment]
@BerkSartik bunu yine appten ekleme olacak admin tarafı sadece view mi olacak o kısmı kaçrıdım ben

**Comment by BerkSartik** [comment]
Hocam appte sadece listeleme olacak linkleri samet hoca giricek şeklinde konuşmuştuk. @VB10
