### ISSUE TITLE
[V7 - ADMIN] Girişimciler için link sayfası

### ISSUE THREAD

**Issue by BerkSartik** [VB-CORE/hatayi_yasat#276]
Yeni bir sayfa açılarak girişimcileri kayıt ekranı oluşturulacak. (güncelleme ve silme dahil)

# Girilecek Datalar #
- Logo
- İsim
- Küçük bir açıklama (kesinleştirilmedi)

**Comment by VB10** [comment]
@BerkSartik bu ne için di bu arada hatırlayamadım

**Comment by BerkSartik** [comment]
Girişimci kadınların sayfalarını desteklemek amacıyla uygulama içi satış yapmaktansa ürünleri böyle bir yol izlemiştik. Kadın işletmecinin adı ve linki tıklanınca sayfaya yönlendirme. Burada sadece Samet hoca girecek linkleri @VB10
