### ISSUE TITLE
[V7 - CLIENT] Resmi kurumlara ilçe eklenecek

### ISSUE THREAD

**Issue by BerkSartik** [VB-CORE/hatayi_yasat#277]
- Resmi kurumlar A-Z sıralanıp ilçe bazlı olarak ayrıştırılacak. (Yani en başta ilçe başlığı, altına o ilçede bulunan kurumlar şeklinde)

**Comment by VB10** [comment]
@mysCod3r sen ilçeyi modele eklersin biz gelen listeden ekrana basarız bu taskı ben aldım üstüme

**Comment by burakJs** [comment]
#285 Bu pr da gelistirme yapildi
