### ISSUE TITLE
[V7 - CLIENT] Yeni İşletmelere Konum Pinleme Özelliği

### ISSUE THREAD

**Issue by BerkSartik** [VB-CORE/hatayi_yasat#279]
- Yeni işletme formuna adresi daha net almak adına haritadan anlık konumunu alarak koordinatlarını alma eklenecek.

(Fikrin unutulmaması adına)
Harita üstünde "bana yakın işletmeler" gösterilebilir.

**Comment by VB10** [comment]
@burakJs diğer taskta client demiştim onu bıraklaım bunu berko yapsın ikiniz bilrike konuşrusunuz web admin tarafını böyle bağlarız

**Comment by VB10** [comment]
bunu tamamladım

**Comment by VB10** [comment]
https://github.com/VB-CORE/life_client/pull/286
