### ISSUE TITLE
[V7 - ADMIN] İşletmelere koordinat bilgisi eklenecek

### ISSUE THREAD

**Issue by BerkSartik** [VB-CORE/hatayi_yasat#280]
- İşletme modeline koordinat eklenecek.
- Panel üzerinden yeni işletme ve işletme güncelle kısımlarına koordinat entegresi yapılacak.

**Comment by VB10** [comment]
@burakJs burada yeni eklenen adreslerde konum seçmesini talep edeceğiz client tarafında admin tarafında ise update butonu olacak orada gelen işletmlere lat long girmesini bkeliyorum. ikisini ayırabilirim veya tek sana verebilirim  @burakJs

**Comment by burakJs** [comment]
Tamamdır hocam
