### ISSUE TITLE
[V7] Düzeltilmesi gereken hatalar

### ISSUE THREAD

**Issue by BerkSartik** [VB-CORE/hatayi_yasat#282]
- İşletme saatinde eğer ki işletmenin kapanış saati 00:00 ise kapalı gözükme problemi oluyor. 23:59 yapınca düzeliyor.

**Comment by VB10** [comment]
@mysCod3r burada admin tarafında girilen sürede bir sıkıntı oluyor bizde mobilde bunu anlayamadığımız için saat geçmişmi geçmemiş mi bilemiyoruz. burada iki çözümümüz yapılabilir ya AM PM gibi bir açılış saatlerine update atıcaz veya bundan sonrakiler öyle olacak.

yada öneriniz var mı konuşalım

**Comment by VB10** [comment]
@BerkSartik @burakJs  fikir var mı dostlar

**Comment by mysCod3r** [comment]
https://github.com/VB-CORE/life_shared/pull/53

bugfix/ys/store-model-helper
@VB10  @BerkSartik  @burakJs müsaitliği olan shared i bu branchten ref alarak test edebilir misiniz
