### ISSUE TITLE
Proje liste sayfası

### ISSUE THREAD

**Issue by VB10** [VB-CORE/hatayi_yasat#40]
Bu sayfa tabın ikinci sayfası burada amacımız ekteki gibi bir görsel yapmak olacak

üstte bir slider istiyorum buradaki data yine backendden gelecek ve altındaki list bu şekilde bir 2li grid olacak içi dolarak gidecek
yüklenirken önceki sayfad kulalnılan shimmer effect verilecek
<img width="351" alt="image" src="https://github.com/VB-CORE/life_client/assets/17102578/3b8ca6da-5261-40f1-bbcd-81271a7449fc">

**Comment by VB10** [comment]
@mysCod3r eklenecekelr
- gelecek listede end date değeri geçmiş olanlar listede gözükmeyecek
- https://pub.dev/packages/carousel_slider bu paket eklenecek ve en ustte ilk iki kampanya resmi gözükecek var ise eğer hiç kampanya yoksa direk empty ekran göüzkecek
- bu paketin önüne customslider tarzı ufak widget yazıp image listesi alıp dokunduğnu veren eklenebilir dokunulan itemin detayına gidecek

**Comment by mysCod3r** [comment]
hocam ben modeli #42 de yazanlara göre ekledim. 
projelerin zaten list<image> değeri var, cover foto boşsa listenin ilkini basıyorum ekrana. 
anlamadığım şu: slider ile kaydırma yaparken projeleri mi kaydıracağım yoksa projenin kendi görsellerini mi 
hocam bir de siz kampanya diye yazmışsınız ama issue adı project diye ben her şeyi project olarak yazdım ikisi aynı şey mi ona göre kampanyaya çevireyim
