### ISSUE TITLE
search ekranı yeni alan

### ISSUE THREAD

**Issue by VB10** [VB-CORE/hatayi_yasat#43]
burada girilen kelime sonuçları artk ekranda tablı gözükecek
ilk tab mekanlar ikinicsi projeler

bunlar tıklaınca detaya gidilecek

**Comment by VB10** [comment]
@emreydz buna calsıtım dedın ama ne yaptın ne ettin ne brnach var ne push bir paylaşırsan bilelim

**Comment by emreydz** [comment]
Hocam #40 #41 in bitmesini bekliyordum push atmadım bu yüzden. Ui anlamında geliştirme yapabildim.

**Comment by VB10** [comment]
bunu v3 atiyorum suanlik sadece mekan arama aktif olsun istiyorum @BerkSartik
