### ISSUE TITLE
push yeni projeler için

### ISSUE THREAD

**Issue by VB10** [VB-CORE/hatayi_yasat#44]
burada backedn yeni bir type dönecek ve buna göre aynı mekanlardaki logicler bu projeler sayfalarına yönlenecek.

**Comment by VB10** [comment]
@MehmetKaranlik bunun entegrasyonu yapıldıysa type verır mısın

**Comment by BerkSartik** [comment]
/topics/campaigns

**Comment by MehmetKaranlik** [comment]
@BerkSartik  @VB10 https://github.com/VB-CORE/life_shared/pull/11 buradaki modeli alıp update edebilirsiniz
gelebilecek olasılıkları yazdım burada.

**Comment by MehmetKaranlik** [comment]
bunu çözdük kapatıyom
