### ISSUE TITLE
hotfix v1.0.1

### ISSUE THREAD

**Issue by BerkSartik** [VB-CORE/hatayi_yasat#47]
- **Force update android ios redirect link**
- **Android (gerçek cihazlarda) splash logo kalitesiz ve büyük duruyor**
- **Mekan ismi çok uzunsa taşıyor**
- **Uygulama içindeki site urlsinde "www" olmadığı açılmıyor.**

### **_Kullanımı bozmayan ancak görüntü olarak kötü duranlar_**

- Onboard resmi center gerekli
![image](https://github.com/VB-CORE/life_client/assets/48359825/1a8c0356-9fca-43e2-abd3-cd1ee1dfc5ff)

- Telefon numarası client'dan 505105105 olarak gidiyor. Adminden girildiğinde 0(515) 515-52 şeklinde görünüyor.

![image](https://github.com/VB-CORE/life_client/assets/48359825/4a3724ba-934f-40c7-981d-70c237f79dcd)
![image](https://github.com/VB-CORE/life_client/assets/48359825/7d22cf9c-a388-42e9-90b6-d552e658e91a)

**Comment by VB10** [comment]
town filtre eklenecek

**Comment by VB10** [comment]
tamamlandi
