### ISSUE TITLE
Apple Cihazlarda Harita Yönlendirme Bug

### ISSUE THREAD

**Issue by burakJs** [VB-CORE/hatayi_yasat#55]
- Apple cihazlarda harita yönlendirmelerde hem native hem web tarafında harita açılıyor

https://github.com/VB-CORE/life_client/assets/70351342/d73caef9-02d0-48c5-a397-9759f367c230

**Comment by VB10** [comment]
bu olmamış burada yapılması gereken if ios değil çünkü andorided aynısı olaiblir
catch blocklarının içine o kod alınmalı ve bakılmalı böyle yapar atar mısın @burakJs

**Comment by VB10** [comment]
cozdum bye
