### ISSUE TITLE
Bugs that will be fixed with v2

### ISSUE THREAD

**Issue by BerkSartik** [VB-CORE/hatayi_yasat#57]
- [x] "Mekan ara" çubuğuna basıp arama yapıldıktan sonra, aranan kelimeye göre mekanlar listeleniyor. Ancak klavyenin sağ alt köşesindeki arama düğmesine basılırsa mekanlar bir anda kayboluyor. Ardından tekrar arama çubuğuna tıklanırsa mekanlar tekrar görünmeye başlıyor. Aynı zamanda klavyedeki arama düğmesi yerine geri tuşuna basarak klavye kapatılırsa aramalar kaybolmuyor, görünür kalmaya devam ediyor. Bu hatanın videosuna [buradan ulaşabilirsin](https://drive.google.com/file/d/1T3UFbWiqwNtgmM40-CDPgheUN9X4cwpC/view?usp=sharing).

- [x] Herhangi bir mekanın detaylarına girdikten sonra paylaş butonuna bir kaç defa arka arkaya hızlıca tıklanırsa paylaşma diyalogu kapatıldıktan sonra (kaç kere tıklandıysa) tekrar açılıyor. İlgili [video](https://drive.google.com/file/d/1TF_2hErrfQnjGwmbaPWuuikMnb4UOhQL/view?usp=sharing).

- [x] Uygulamanın Türkçe dilinde filtreleme diyaloğundaki butonun yazısı "Listele" iken [İngilizce'sinde](https://drive.google.com/file/d/1TQdb2bSON0ZdD2WRwpulxPdvD3EGowBU/view?usp=sharing) "lists" olarak adlandırılmış. Butonun yazısı "lists" yerine "List" olmalı.

- [x] Yine uygulamanın Türkçe sürümünde herhangi bir mekanın detaylarına girip telefon numarasına tıklandığında açılan [dialog'da](https://drive.google.com/file/d/1TWXsl6xALdFea0HtjyIziI8FJ80HLh5q/view?usp=sharing) "Telefon ile arama yapmak ister misiniz?" yazarken İngilizce'sinde "Search by phone" yazıyor. Bunun çevirisi de "Would you like to call by phone?" şeklinde olursa daha doğru olacaktır.

- [x] Yine mekan detayları ekranında adres bilgisine tıklandığında açılan [dialog'da](https://drive.google.com/file/d/1TZIx41onXv9omv22q8l8AIQQ1_1_0P3V/view?usp=sharing) Türkçe olarak "Adresi haritada açmak ister misiniz?" diye bir mesaj görünürken İngilizce çevirisinde "Address Open on the Map" yazıyor. Bunun çevirisi "Would you like to open the address on the map?" olursa daha doğru olacaktır.

- [x] Ayarlar ekranında henüz aktif olmayan [switch'in](https://drive.google.com/file/d/1Tfb38WpTMqvA7zeCZoM4Co4MjHPdaGWl/view?usp=sharing) adı "Tema" olarak görünüyor, ancak koyu tema geçişlerinde kullanılan bir özelliğe benziyor, bunun adının "Koyu Tema" ya da "Karanlık Tema" olması gerektiğini düşünüyorum.

- [x] Geliştiriciler ekranında "Profili Görüntüle" butonuna tıklandığında görüntülenen ripple effect kutunun dışına çıkıyor, bu durum gözden kaçmış gibi görünüyor (Tabi think outside the box göndermesi falan varsa bilemem 😅). Bunu da belirtmek istedim. Bunun da videosuna [buradan](https://drive.google.com/file/d/1TJkz4hmTOcHpojopofDWTH5HTiSAc8Mt/view?usp=sharing) ulaşabilirsin.

- [x] Ana ekrandaki search bar'ın hint'i İngilizce'ye "Search Place" olarak çevrilmiş ancak bunun "Search for places" olarak çevrilmesi gerekiyor.

**Comment by emreydz** [comment]
@VB10 Hocam sormadan yapmiyim dedim permission_handler paketi kullanarak red durumunda popup çıkarıp ayarlara yönlendirme tarzı bir kurgu olsun mu ? Ya da siz nasıl isterseniz
