### ISSUE TITLE
İnternet Kontrolü

### ISSUE THREAD

**Issue by mysCod3r** [VB-CORE/hatayi_yasat#62]
Uygulamada internet kontrolünü Splash içerisinde yapıyoruz. Fakat FirebaseRemoteConfig Splash ten önce çalıştığı için eğer internet yoksa uygulama splashte donup kalıyor. İnternet kontrolünün FirebaseRemoteConfig çağrılmadan önce yapılması gerekiyor

ApplicationInit içerisinde 40. satır

**Comment by VB10** [comment]
fixed this issue i found couple of other problems in ssplash view so i already added all
