### ISSUE TITLE
request permission again, KVKK text and visual problems

### ISSUE THREAD

**Issue by BerkSartik** [VB-CORE/hatayi_yasat#63]
### Permission

- [x] Kullanıcı kamera ya da galeri izni vermediği zaman bug'a giriyor. Fotoğraf eklemek istemesi durumunda izini değiştirmek için  uygulamanın ayarlar kısmına yönlendirme yapılmalı.

- [x] Bildirimlere onay verilmeme durumu için settings'e bildirim ayarları adı altında alan ekleyip tekrar izin isteyebiliriz.

-----

- [x] KVKK Metni "SESİNİ DUYDUMA" ait. Hatay'ı Yaşat özelinde yeni metin hazırlayabiliriz.

- [x] Extended body "true" olduğu için en alta kaydırınca 1 tane item yarım gözüküyor

![image](https://github.com/VB-CORE/life_client/assets/48359825/a0e9c1ec-3bf8-4db2-bc28-7ffec2e2cdd2)

**Comment by VB10** [comment]
fixed this issue expect kvvk text field
