### ISSUE TITLE
[Client]  Ana sayafada fab button ile  firma giriş ekranı

### ISSUE THREAD

**Issue by VB10** [VB-CORE/hatayi_yasat#7]
Burada firmalar kendi bililerini girecek

- Fotoğraf
- Firma adı
- Firma adresi
- Olduğu ilçe seçiliecek
hepsi required alanlar olup doldurulmadan geçilmeyecek,

işlem başarılı olursa popup başarılı diyilip adama admin onayı sornası listede gözüecek diye ekliyor olacağız

**Comment by BerkSartik** [comment]
This issue has been completed in branch #14.
