### ISSUE TITLE
proje ekleme değişiklikleri

### ISSUE THREAD

**Issue by BerkSartik** [VB-CORE/hatayi_yasat#70]
- [x] End date kalkıp sadece başlangıç girilmeli

 - [x]  Saat kısmı eksik

- [ ] İletişim eksik

**Comment by BerkSartik** [comment]
Phone shared'a eklendi. PR merge'den sonra sayfalar(ekleme ve detay) buna göre güncellenecek.

https://github.com/VB-CORE/life_shared/pull/13

**Comment by mysCod3r** [comment]
#74 de eklendi.
