### ISSUE TITLE
Bildirimler sayfasında görüntülenmeyen bildirimlerde highlight eklenecek

### ISSUE THREAD

**Issue by mysCod3r** [VB-CORE/hatayi_yasat#80]
Bildirimler sayfasındaki datalar için kullanıcının son girişinden sonra gelen bildirimlere highlight eklenecek.

**Comment by VB10** [comment]
@mysCod3r sen buna başlar mısın önden

- push sayfasıan her girilidğinde bir last date diye değer saklıyacağız bunu şuanlık shared içine koyaiblirz sonradan hive alacağız
- her yeni geldiğinde bu dateden büyük olanların rengini açık renkli diğerleri soluk olacak

**Comment by mysCod3r** [comment]
@VB10 tamamdır hocam taski aldım bu gece bakmayı düşünüyorum

**Comment by mysCod3r** [comment]
@VB10 hocam şuanlık bu şekilde ayarladım. koyu olanlar cache deki son date den sonra, beyaz olanlar son date den önce.
sorum şu buradaki logici nasıl yönetelim? sayfadan geri dönerken mi cachedeki date i güncellemeliyim yoksa sayfa açıldıktan belli bir süre sonra mı?

![image](https://github.com/VB-CORE/life_client/assets/76634747/e8077bfe-6ff7-44e6-b6d7-7423748c05f9)
