### ISSUE TITLE
iş yeri ve burs sekmesi

### ISSUE THREAD

**Issue by VB10** [VB-CORE/hatayi_yasat#88]
bu altta ilanlar olarak yeni bir tab olacak

- bu alanda hem iş ilanları 
- ikili grid tasarımı burada aktif olacak
- detaya gittiğinde iligli datalar alt alta gösterilecek
- n firma adı, İletişim pozisyon, bay/bayan, özel şartlar ile açabilir. bu datalar göüzkecek soru varsa yine samete danışalacak @MehmetKaranlik 
- paylaş butonu aktif olacak datalar title ve body olarak paylaşılabilir olsun title da sadece ek hatayı yaşatı ekleyeilbielim veya tarafıdnan gibi

**Comment by mysCod3r** [comment]
@VB10 hocam bu task yapılacak mı? https://x.com/grafikherif/status/1713260387120910766?s=46 burda böyle bir konuşma geçmiş ama sizin haberiniz var mı

**Comment by VB10** [comment]
iş yeri kısmı kesin olacak bursu almayı sonradan toplayaiblir iş yeri eklemeyi @MehmetKaranlik de bağlamış olmalı

**Comment by mysCod3r** [comment]
@MehmetKaranlik hocam merge alınmış pr lara baktım ama göremedim gözümden kaçmış olabilir size sorayım dedim yaptığınız bir geliştirme oldu mu
