### ISSUE TITLE
Burs isteme

### ISSUE THREAD

**Issue by VB10** [VB-CORE/hatayi_yasat#89]
orta butonlara üçücü burs rqeesut ekranı gelecek

- Öğrenci burs eşleştirme, bunu bir yerde göstermeyeceğiz. Öğrenci sadece başvuru yapacak, öğrenci belgesi ile, iletişim ve hikayesini yazmak icin bi kısım olacak
- iletişim için tel ve mail adresi istenir edulu bir mail adresi isteyerek ozrlayaibliriz
- bu datalar istenecek
- pdf kabul edilip maks 0.5kb olacak yeterli gibi geldi @MehmetKaranlik burs ilanları silindikten sonra veye onalyanıdktan sonra kişilerin pdfleri sistemden silinemli
- işlem onalyıkdtan sonra sistem tarafından bilgi verilecek sizlere denielbilir

**Comment by VB10** [comment]
@burakJs @selim1238 bilrikte çalışır mısınız burada

**Comment by burakJs** [comment]
Olur hocam benim için

**Comment by zog06** [comment]
ortak bir zaman ayarlayalım @burakJs

**Comment by burakJs** [comment]
- Hocam bugün genel olarak tasarımı yapıldı. Yarın da logic tarafının yazılıp cumartesiye kadar bitmesi planlanıyor. @VB10 

<img src="https://github.com/VB-CORE/life_client/assets/70351342/8427795c-dc8d-443b-8061-796179d9cc96" width=300>
